image: openjdk:17

stages:
  - test
  - deploy

before_script:
  - PATH=/opt/apache-maven-3.8.6/bin:/usr/local/openjdk-17/bin:$PATH
  - JAVA_HOME=/usr/local/openjdk-17

test-all:
  stage: test
  tags: [maven]
  except:
    - master
    - main
  script:
    - mvn clean install

test-unit:
  stage: test
  tags: [maven]
  only:
    - master
    - main
  script:
    - mvn clean package
    - cp target/testingMicroservices*.jar testingMicroservices-${CI_COMMIT_SHA}.jar
  artifacts:
    name: testingMicroservices
    expire_in: 1 week
    paths:
      - testingMicroservices-${CI_COMMIT_SHA}.jar

deploy:
  stage: deploy
  needs:
    - test-unit
  only:
    - master
    - main
  script:
    - ls testingMicroservices*.jar