image: ricardoazcar/testingmscv:latest

stages:
  - test
  - deploy

#before_script:
#  - PATH=/opt/apache-maven-3.9.0/bin:/usr/local/openjdk-19/bin:$PATH
#  - JAVA_HOME=/usr/local/openjdk-19

test-all:
  stage: test
  tags: [maven]
  except:
    - master
    - main

test-unit:
  stage: test
  tags: [maven]
  only:
    - master
    - main

deploy:
  stage: deploy
  needs:
    - test-unit
  only:
    - master
    - main